### ISSUE TITLE
Downloads of Tools to flash the default firmware are corrupt

### ISSUE THREAD

**Issue by loadedlouie** [boseji/ESP-Store#2]
Downloads of Tools to flash the default firmware are corrupt, please check it out.

**Comment by boseji** [comment]
Thanks for your input,
Can you specify which particular File you are facing the issue ?
https://github.com/boseji/ESP-Store/tree/master/tools

**Comment by boseji** [comment]
Also please specify the target board and Platform.
(ESP32 or ESP8266/85)
Since some times due to incompatibility to board leads to such problems.
